version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Installing source dependencies...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing image to ECR...
    
artifacts:
  files: imagedefinitions.json
